<%@ Page %>
<HTML>
	<HEAD>
		<title>考试管理规定</title>
		<meta name="GENERATOR" Content="Microsoft Visual Studio .NET 7.1">
		<meta name="CODE_LANGUAGE" Content="C#">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
		<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
		<link rel="stylesheet" href="../_style/right.css" type="text/css">
	</HEAD>
	<body oncontextmenu="window.event.returnValue=false" ondragstart="window.event.returnValue=false"
		onsource="window.event.returnValue=false" leftmargin="0" topmargin="0">
		<table border="0" width="100%" height="100%" cellspacing="0" cellpadding="0" align="center">
			<tr>
				<td width="100%" height="95%" valign="top" align="center">
					<table width="95%" border="0" cellspacing="0" cellpadding="0" align="center">
						<tr>
							<td valign="top" width="100%"><br>
								<PRE>
            <!--#include file='../_Data/TXT/KW_GLGD.txt'-->
            <br></PRE>
							</td>
							<PRE></PRE>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</body>
</HTML>
