<%@ Page Language="C#" %>
<HTML>
	<HEAD>
		<title>青果教务</title>
		<meta name="GENERATOR" Content="Microsoft Visual Studio .NET 7.1">
		<meta name="CODE_LANGUAGE" Content="C#">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
		<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
		<link href="../_style/Styles_Rpt.css" rel="stylesheet" type="text/css">
	</HEAD>
	<body oncontextmenu=window.event.returnValue=false onselectstart=window.event.returnValue=false ondragstart=window.event.returnValue=false onsource=window.event.returnValue=false leftmargin="0" topmargin="0">
	<table width="100%" border="0" cellspacing="0" cellpadding="0" height="100%">

	<tr><td valign="top" align="center" height="100%">
	<iframe name=main src="../_data/RULE/glgd.aspx?href=KW_GLGD.xml" width=100% height=100% frameborder=0></iframe>
	</td></tr> 

</table>
</body>
</html>
